source 'https://rubygems.org'

gem 'sinatra'
gem 'slim'
gem 'sqlite3'
gem 'rerun'
gem 'bcrypt'
gem 'byebug'
gem 'rack-flash3'
gem 'capybara'
gem 'rspec'
gem 'sass'
gem 'selenium-webdriver'
gem 'racksh'
gem 'sass-globbing'
gem "webdrivers"
gem 'ruby-debug-ide'
gem 'debase'
gem 'yard'
gem 'yard-sinatra', git: 'https://github.com/chrisb/yard-sinatra'